version: '3.2'
services:
  postgres:
    image: "postgres:21"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  geth:
    image: "matterlabs/geth:latest"
    environment:
      - PLUGIN_CONFIG=fast

  dev-ticker:
    image: "matterlabs/dev-ticker:latest"
    volumes:
      - ./etc/tokens/:/etc/tokens

  dev-liquidity-token-watcher:
    image: "matterlabs/dev-liquidity-token-watcher:latest"
    env_file:
      - ./etc/env/docker.env
    volumes:
      - ./etc/tokens/:/etc/tokens

  zk:
    image: "matterlabs/zk-environment:latest"
    depends_on:
      - postgres
      - geth
      - dev-ticker
      - dev-liquidity-token-watcher
    command: tail -f /dev/null
    volumes:
      - .:/usr/src/zksync
      - /usr/src/cache:/usr/src/cache
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - IN_DOCKER=true
      - CACHE_DIR=/usr/src/cache
      - SCCACHE_CACHE_SIZE=50g
      - SCCACHE_GCS_BUCKET=matterlabs-infra-sccache-storage
      - SCCACHE_GCS_OAUTH_URL=http://169.254.169.254/computeMetadata/v1/instance/service-accounts/gha-ci-runners@matterlabs-infra.iam.gserviceaccount.com/token
      - SCCACHE_GCS_RW_MODE=READ_WRITE
      - SCCACHE_ERROR_LOG=/tmp/sccache_log.txt
      - CI=1
